import type { BreakingChange } from '../diff/engine';
import type { TestFixResult } from '../fixer/test-fixture-fixer';
import type { ValidationStepResult } from '../validation/runner';

/**
 * Build the full Pull Request description: breaking changes → fixes → test
 * fixture remediation → the Warden validation sandbox results → overall
 * verdict → error logs. This is what earns reviewer trust by proving the
 * migration was actually verified.
 */
export function generatePRBody(
  breakingChanges: readonly BreakingChange[],
  fixesApplied: readonly unknown[],
  validationResults: ValidationStepResult[],
  testFixtures: readonly TestFixResult[] = [],
): string {
  const lines: string[] = [];

  lines.push('# 🤖 Mantior API Migration', '');
  lines.push(
    'This PR was automatically generated by Mantior to remediate breaking changes detected in the upstream API spec.',
    '',
  );

  // 1. Breaking Changes Summary
  lines.push('## ⚠️ Breaking Changes Detected');
  for (const change of breakingChanges) {
    lines.push(`- **${change.type}**: ${describeChange(change)}`);
  }
  lines.push('');

  // 2. Fixes Applied
  lines.push('## 🛠 Fixes Applied', '');
  lines.push(`Mantior applied **${fixesApplied.length}** automated fixes across this repository.`);
  lines.push('*Review the "Files Changed" tab for exact diffs.*', '');

  // 2b. Test Fixture Remediation (only when test files were touched)
  if (testFixtures.length > 0) {
    const totalMocks = testFixtures.reduce((sum, fixture) => sum + fixture.mocksUpdated, 0);
    const totalAssertions = testFixtures.reduce(
      (sum, fixture) => sum + fixture.assertionsUpdated,
      0,
    );
    lines.push('## 🧪 Test Fixture Remediation', '');
    lines.push(
      'Mantior detected that the source code changes required updates to your test mocks and assertions to keep the suite green.',
      '',
    );
    lines.push('| Test File | Mocks Updated | Assertions Updated |');
    lines.push('|---|---|---|');
    for (const fixture of testFixtures) {
      lines.push(
        `| \`${fixture.file}\` | ${fixture.mocksUpdated} | ${fixture.assertionsUpdated} |`,
      );
    }
    lines.push('');
    lines.push(
      `**Total:** ${totalMocks} mocks and ${totalAssertions} assertions automatically updated to match the new API contract.`,
      '',
    );
  }

  // 3. Validation Results (The Trust Builder) — only when validation ran.
  if (validationResults.length > 0) {
    lines.push('## 🧪 Validation Sandbox Results', '');
    lines.push(
      'Mantior cloned this repository into an isolated, network-restricted sandbox and executed your build/test pipeline to verify the migration.',
      '',
    );
    lines.push('| Step | Status | Details | Duration |');
    lines.push('|---|---|---|---|');
    for (const res of validationResults) {
      lines.push(
        `| **${escapeCell(res.name)}** | ${statusCell(res)} | ${detailsCell(res)} | ${durationCell(res)} |`,
      );
    }
    lines.push('');

    // 4. Overall Verdict — required steps must pass; optional failures are warnings.
    const allRequiredPassed = validationResults.every(res => res.success || !res.required);
    if (allRequiredPassed) {
      lines.push('### ✅ Overall Verdict: SAFE TO MERGE', '');
      lines.push(
        'All required validation steps passed. The API migration is syntactically and functionally verified.',
        '',
      );
    } else {
      lines.push('### ⚠️ Overall Verdict: MANUAL REVIEW REQUIRED', '');
      lines.push(
        'One or more required validation steps failed. Please inspect the errors below and adjust the migration manually.',
        '',
      );
    }
  }

  // 5. Error Logs (Collapsible)
  const failedSteps = validationResults.filter(res => !res.success && res.error);
  if (failedSteps.length > 0) {
    lines.push('<details>');
    lines.push('<summary>📋 View Error Logs</summary>', '');
    for (const fail of failedSteps) {
      lines.push(`**${escapeCell(fail.name)}**`);
      lines.push('```bash');
      lines.push(fail.error ?? '');
      lines.push('```');
    }
    lines.push('</details>', '');
  }

  // 6. Footer
  lines.push('---');
  lines.push('*Generated by [Mantior](https://github.com/davidnitty/Mantior) • Autonomy Level 4*');

  return lines.join('\n');
}

function describeChange(change: BreakingChange): string {
  if (change.property && change.newProperty) {
    return `\`${change.property}\` → \`${change.newProperty}\``;
  }
  if (change.oldValue && change.newValue) {
    return `\`${change.oldValue}\` → \`${change.newValue}\``;
  }
  return change.message;
}

function statusCell(res: ValidationStepResult): string {
  if (res.success) {
    return '✅ Pass';
  }
  return res.required ? '❌ Fail' : '⚠️ Warn';
}

function detailsCell(res: ValidationStepResult): string {
  const tr = res.testResults;
  if (tr) {
    if (tr.failed > 0) {
      return `**${tr.failed} failed**, ${tr.passed} passed (out of ${tr.total})`;
    }
    return `**${tr.passed}/${tr.total} passed** (${tr.framework})`;
  }
  if (!res.success && res.error) {
    return `\`Exit code: ${res.exitCode}\``;
  }
  return 'Completed';
}

function durationCell(res: ValidationStepResult): string {
  return `${(res.durationMs / 1000).toFixed(1)}s`;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}
